---
- name: RKE2 Cluster Cleanup Playbook
  hosts: all
  become: true
  gather_facts: false
  strategy: linear

  tasks:
    - name: Warning - RKE2 will be removed
      ansible.builtin.pause:
        prompt: "This will completely remove RKE2 from all nodes. Press ENTER to continue or CTRL+C to abort"
      delegate_to: localhost

    - name: Stop and disable all RKE2-related services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
      with_items:
        - rke2-server
        - rke2-agent
      failed_when: false

    - name: Wait for processes to be killed
      ansible.builtin.wait_for:
        timeout: 30
        host: localhost
        port: 6443
        state: stopped
      delegate_to: localhost
      failed_when: false