---
- name: Configure kubectl access
  hosts: control_plane_nodes
  gather_facts: true
  become: true

  tasks:
    - name: Ensure kubectl directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      loop:
        - "{{ kubectl.config.user | dirname }}"
        - "{{ kubectl.config.root | dirname }}"

    - name: Create symlinks for kubectl config
      ansible.builtin.file:
        src: "{{ kubectl.config.source }}"
        dest: "{{ item }}"
        state: link
        force: true
      loop:
        - "{{ kubectl.config.user }}"
        - "{{ kubectl.config.root }}"

    - name: Set KUBECONFIG environment variable
      ansible.builtin.lineinfile:
        path: "{{ item }}"
        line: "export KUBECONFIG={{ kubectl.config.source }}"
        regexp: "^export KUBECONFIG="
        create: true
      loop:
        - "{{ paths.user.bashrc }}"
        - "{{ paths.system.root_bashrc }}"
