---
collections:
  - name: kubernetes.core
    version: ">=2.4.0"
  - name: community.general
    version: ">=6.0.0"

roles:
  - src: https://github.com/yourusername/rke2_cluster.git
    name: rke2_cluster
    scm: git
    version: main
