---
collections:
  - name: kubernetes.core
    version: ">=2.4.0"
  - name: community.general
    version: ">=6.0.0"

roles:
  - src: https://github.com/lucas-albers-lz4/rke2setup.git
    name: rke2_cluster
    scm: git
    version: main
