- name: Deploy Six Node RKE2 Cluster
  hosts: six_node_cluster
  gather_facts: true
  strategy: linear
  
  pre_tasks:
    - name: Verify control plane nodes are defined
      ansible.builtin.assert:
        that: groups['control_plane_nodes'] | length > 0
        fail_msg: "No control plane nodes defined"
      run_once: true
      delegate_to: localhost
      become: false

  roles:
    - role: rke2_cluster