---
- name: Deploy Six Node RKE2 Cluster
  hosts: six_node_cluster
  gather_facts: true
  become: true

  pre_tasks:
    - name: Set cluster type
      ansible.builtin.set_fact:
        cluster_type: "six_node"
        first_server_ip: "{{ hostvars[groups['control_plane_nodes'][0]]['ansible_host'] }}"

    - name: Set TLS SANs
      ansible.builtin.set_fact:
        tls_sans: "{{ groups['six_node_cluster'] | map('extract', hostvars, ['ansible_host']) | list }}"

  roles:
    - role: rke2_cluster
