---
- name: Deploy Three Node RKE2 Cluster
  hosts: three_node_cluster
  become: true
  gather_facts: true
  
  pre_tasks:
    - name: Set cluster type
      set_fact:
        cluster_type: "{{ hostvars[inventory_hostname]['cluster_type'] | default('three_node') }}"

  roles:
    - role: rke2-cluster
