---
- name: Deploy Three Node RKE2 Cluster
  hosts: three_node_cluster
  gather_facts: true
  become: true

  roles:
    - role: rke2_cluster
      vars:
        cluster_type: three_node
        first_server_ip: "{{ hostvars[groups['three_node_control_plane'][0]]['ansible_host'] }}"
