---
all:
  children:
    six_node_cluster:
      children:
        control_plane_nodes:
          hosts:
            k1:
              ansible_host: 192.168.1.23
            k2:
              ansible_host: 192.168.1.24
            k3:
              ansible_host: 192.168.1.25
  vars:
    ansible_user: ubuntu
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
