---
- name: Wait for cluster to be ready before installing add-ons
  ansible.builtin.command:
    cmd: kubectl wait --for=condition=Ready nodes --all --timeout=300s
  environment:
    KUBECONFIG: /etc/rancher/rke2/rke2.yaml
  delegate_to: "{{ groups['control_plane_nodes'][0] }}"
  run_once: true

- name: Add required Helm repositories
  kubernetes.core.helm_repository:
    name: "{{ item.name }}"
    repo_url: "{{ item.url }}"
  loop:
    - { name: 'ingress-nginx', url: 'https://kubernetes.github.io/ingress-nginx' }
    - { name: 'prometheus-community', url: 'https://prometheus-community.github.io/helm-charts' }
  delegate_to: "{{ groups['three_node_control_plane' if cluster_type == 'three_node' else 'control_plane_nodes'][0] }}"
  run_once: true

- name: Install MetalLB
  when: install_metallb | bool
  block:
    - name: Create MetalLB namespace
      kubernetes.core.k8s:
        kubeconfig: /etc/rancher/rke2/rke2.yaml
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: metallb-system
      delegate_to: "{{ groups['control_plane_nodes'][0] }}"
      run_once: true

    - name: Deploy MetalLB configuration
      kubernetes.core.k8s:
        kubeconfig: /etc/rancher/rke2/rke2.yaml
        state: present
        src: templates/metallb-config.yml.j2
      delegate_to: "{{ groups['control_plane_nodes'][0] }}"
      run_once: true

- name: Verify MetalLB deployment
  when: install_metallb | bool
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: metallb-system
    label_selectors:
      - app=metallb
  register: metallb_pods
  until: metallb_pods.resources | length > 0
  retries: 10
  delay: 10
  delegate_to: "{{ groups['three_node_control_plane' if cluster_type == 'three_node' else 'control_plane_nodes'][0] }}"
  run_once: true

- name: Install monitoring stack
  when: install_monitoring | bool
  block:
    - name: Create monitoring namespace
      kubernetes.core.k8s:
        kubeconfig: /etc/rancher/rke2/rke2.yaml
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: monitoring
      delegate_to: "{{ groups['three_node_control_plane' if cluster_type == 'three_node' else 'control_plane_nodes'][0] }}"
      run_once: true

    - name: Deploy Prometheus stack
      kubernetes.core.helm:
        kubeconfig: /etc/rancher/rke2/rke2.yaml
        name: prometheus
        chart_ref: prometheus-community/kube-prometheus-stack
        release_namespace: monitoring
        values_files:
          - files/monitoring/prometheus-values.yml
      delegate_to: "{{ groups['three_node_control_plane' if cluster_type == 'three_node' else 'control_plane_nodes'][0] }}"
      run_once: true
      register: prometheus_install
      until: prometheus_install is not failed
      retries: 3
      delay: 10

- name: Install NGINX Ingress Controller
  when: install_ingress | bool
  kubernetes.core.helm:
    kubeconfig: /etc/rancher/rke2/rke2.yaml
    name: ingress-nginx
    chart_ref: ingress-nginx/ingress-nginx
    release_namespace: ingress-nginx
    create_namespace: true
  delegate_to: "{{ groups['three_node_control_plane' if cluster_type == 'three_node' else 'control_plane_nodes'][0] }}"
  run_once: true

- name: Verify Ingress Controller deployment
  when: install_ingress | bool
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: ingress-nginx
    label_selectors:
      - app.kubernetes.io/component=controller
  register: ingress_pods
  until: ingress_pods.resources | length > 0
  retries: 10
  delay: 10
  delegate_to: "{{ groups['three_node_control_plane' if cluster_type == 'three_node' else 'control_plane_nodes'][0] }}"
  run_once: true
