---
- name: Include prerequisites tasks
  ansible.builtin.import_tasks: prerequisites.yml
  tags: ['prereq']

- name: Include SSH setup tasks
  ansible.builtin.import_tasks: ssh_setup.yml
  tags: ['ssh']

- name: Deploy first control plane node
  ansible.builtin.import_tasks: first_control_plane.yml
  when: inventory_hostname == (groups['three_node_control_plane'][0] if cluster_type == 'three_node' else groups['control_plane_nodes'][0])
  tags: ['control-plane']

- name: Deploy additional control plane nodes
  ansible.builtin.import_tasks: additional_control_planes.yml
  when: 
    - cluster_type == 'six_node'
    - inventory_hostname in groups['control_plane_nodes']
    - inventory_hostname != groups['control_plane_nodes'][0]
  tags: ['control-plane']

- name: Deploy worker nodes
  ansible.builtin.import_tasks: workers.yml
  when: 
    - inventory_hostname in (groups['three_node_workers'] if cluster_type == 'three_node' else groups['worker_nodes'])
  tags: ['workers']

- name: Install cluster add-ons
  ansible.builtin.import_tasks: addons.yml
  when: inventory_hostname == (groups['three_node_control_plane'][0] if cluster_type == 'three_node' else groups['control_plane_nodes'][0])
  tags: ['addons']

- name: Validate cluster deployment
  ansible.builtin.import_tasks: validation.yml
  when: inventory_hostname == (groups['three_node_control_plane'][0] if cluster_type == 'three_node' else groups['control_plane_nodes'][0])
  tags: ['validate']
