---
- name: Validate cluster nodes
  block:
    - name: Check cluster health
      ansible.builtin.command:
        cmd: kubectl get --raw '/healthz'
      environment:
        KUBECONFIG: /etc/rancher/rke2/rke2.yaml
      register: health_status
      failed_when: health_status.stdout != 'ok'
      delegate_to: "{{ groups['three_node_control_plane' if cluster_type == 'three_node' else 'control_plane_nodes'][0] }}"
      run_once: true

    - name: Check node status
      ansible.builtin.command:
        cmd: kubectl get nodes -o wide
      environment:
        KUBECONFIG: /etc/rancher/rke2/rke2.yaml
      register: node_status
      delegate_to: "{{ groups['three_node_control_plane' if cluster_type == 'three_node' else 'control_plane_nodes'][0] }}"
      run_once: true

    - name: Display node status
      ansible.builtin.debug:
        var: node_status.stdout_lines
      run_once: true

    - name: Check pod status across all namespaces
      ansible.builtin.command:
        cmd: kubectl get pods --all-namespaces
      environment:
        KUBECONFIG: /etc/rancher/rke2/rke2.yaml
      register: pod_status
      delegate_to: "{{ groups['three_node_control_plane' if cluster_type == 'three_node' else 'control_plane_nodes'][0] }}"
      run_once: true

    - name: Display pod status
      ansible.builtin.debug:
        var: pod_status.stdout_lines
      run_once: true

    - name: Verify cluster version
      ansible.builtin.command:
        cmd: kubectl version --short
      environment:
        KUBECONFIG: /etc/rancher/rke2/rke2.yaml
      register: version_info
      delegate_to: "{{ groups['three_node_control_plane' if cluster_type == 'three_node' else 'control_plane_nodes'][0] }}"
      run_once: true

    - name: Display version information
      ansible.builtin.debug:
        var: version_info.stdout_lines
      run_once: true

    - name: Check control plane components
      ansible.builtin.command:
        cmd: kubectl get pods -n kube-system -l tier=control-plane -o wide
      environment:
        KUBECONFIG: /etc/rancher/rke2/rke2.yaml
      register: control_plane_status
      delegate_to: "{{ groups['three_node_control_plane' if cluster_type == 'three_node' else 'control_plane_nodes'][0] }}"
      run_once: true
