---
- name: Create RKE2 config directory on workers
  ansible.builtin.file:
    path: /etc/rancher/rke2
    state: directory
    mode: '0755'

- name: Configure worker nodes
  ansible.builtin.template:
    src: config.yaml.j2
    dest: /etc/rancher/rke2/config.yaml
    mode: '0644'
  vars:
    node_type: agent
    is_first_server: false

- name: Download RKE2 agent installation script
  ansible.builtin.get_url:
    url: https://get.rke2.io
    dest: /tmp/install.sh
    mode: '0755'

- name: Install RKE2 agent
  ansible.builtin.command: 
    cmd: INSTALL_RKE2_TYPE=agent INSTALL_RKE2_VERSION={{ rke2_version }} /tmp/install.sh
  args:
    creates: /usr/local/bin/rke2

- name: Verify RKE2 installation
  ansible.builtin.command:
    cmd: rke2 --version
  register: rke2_version_check
  failed_when: rke2_version_check.rc != 0
  changed_when: false

- name: Start and enable RKE2 agent service
  ansible.builtin.systemd:
    name: rke2-agent
    state: started
    enabled: yes
    daemon_reload: yes

- name: Verify RKE2 agent service status
  ansible.builtin.systemd:
    name: rke2-agent
    state: started
  register: service_status
  until: service_status.status.ActiveState == "active"
  retries: 5
  delay: 10

- name: Wait for worker node to be ready
  ansible.builtin.command: 
    cmd: kubectl get nodes {{ inventory_hostname }}
  environment:
    KUBECONFIG: /etc/rancher/rke2/rke2.yaml
  delegate_to: "{{ groups['three_node_control_plane' if cluster_type == 'three_node' else 'control_plane_nodes'][0] }}"
  register: node_status
  until: node_status.rc == 0
  retries: 30
  delay: 10
  changed_when: false
