---
- name: Verify cluster configuration
  ansible.builtin.assert:
    that:
      - inventory_hostname == groups['control_plane_nodes'][0]
    fail_msg: "Add-ons must be installed from the first control plane node"

# Continue with add-ons installation
