---
- name: Verify airgap prerequisites
  include_tasks: verify_airgap.yml
  when: airgap_install | default(false) | bool

- name: Prepare airgap images
  include_tasks: airgap_images.yml
  when: airgap_install | default(false) | bool

- name: Map architecture to RKE2 format
  ansible.builtin.set_fact:
    rke2_arch: >-
      {{
        'amd64' if ansible_architecture == 'x86_64'
        else 'arm64' if ansible_architecture in ['aarch64', 'arm64']
        else ansible_architecture
      }}

- name: Ensure airgap images directory exists on remote
  ansible.builtin.file:
    path: "{{ airgap.paths.images_dir }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  become: true
  when: airgap_install | default(false) | bool

- name: Copy airgap images using standard copy
  ansible.builtin.copy:
    src: "{{ version_dir }}/rke2-images.linux-{{ rke2_arch }}.tar.zst"
    dest: "{{ airgap.paths.images_dir }}/rke2-images.linux-{{ rke2_arch }}.tar.zst"
    mode: '0644'
    owner: root
    group: root
  become: true
  when: airgap_install | default(false) | bool 