---
- name: Stop RKE2 services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  with_items:
    - rke2-server
    - rke2-agent
  failed_when: false

- name: Run RKE2 uninstall script
  ansible.builtin.command:
    cmd: /usr/local/bin/rke2-uninstall.sh
    removes: /usr/local/bin/rke2-uninstall.sh
  failed_when: false

- name: Clean up remaining files and directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/lib/rancher/rke2
    - /var/lib/rancher/rke2/server/db/etcd
    - /var/lib/rancher/rke2/server/cred
    - /var/lib/rancher/rke2/server/tls
    - /etc/rancher/rke2
    - /usr/local/bin/rke2
    - /run/k3s
    - /run/flannel
    - /var/lib/kubelet
    - /var/lib/rancher/rke2
  failed_when: false
