---
- name: Stop RKE2 services
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop:
    - rke2-server
    - rke2-agent
  ignore_errors: true

- name: Pause to allow processes to terminate
  ansible.builtin.wait_for:
    timeout: "{{ timeout_short }}"

- name: Remove RKE2 files and directories
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /var/lib/rancher/rke2
    - /etc/rancher/rke2
    - /usr/local/bin/rke2
    - /usr/local/bin/kubectl
    - /var/lib/kubelet
    - /etc/kubernetes
    - /run/k3s
    - /run/flannel
    - /etc/cni
    - /var/lib/cni

