---
- name: Stop RKE2 services
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop:
    - rke2-server
    - rke2-agent
  ignore_errors: true

- name: Remove RKE2 files and directories
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /var/lib/rancher/rke2
    - /etc/rancher/rke2
    - /usr/local/bin/rke2
    - /usr/local/bin/kubectl
    - /var/lib/kubelet
    - /etc/kubernetes
    - /run/k3s
    - /run/flannel
    - /etc/cni
    - /var/lib/cni

- name: Record uptime before reboot
  shell: cat /proc/uptime | awk '{print $1}'
  register: uptime_before
  changed_when: false

- name: Trigger reboots on all hosts
  reboot:
    msg: "Rebooting after RKE2 cleanup"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    test_command: uptime
  async: 1
  poll: 0

- name: Wait for all hosts to come back
  wait_for_connection:
    connect_timeout: 5
    sleep: 5
    delay: 5
    timeout: 300

- name: Verify reboot occurred
  shell: cat /proc/uptime | awk '{print $1}'
  register: uptime_after
  changed_when: false
  failed_when: uptime_after.stdout | float > uptime_before.stdout | float

- name: Debug reboot status
  debug:
    msg: |
      Host: {{ inventory_hostname }}
      Uptime before: {{ uptime_before.stdout }}
      Uptime after: {{ uptime_after.stdout }}
      Reboot verified: {{ uptime_after.stdout | float < uptime_before.stdout | float }}
