---
- name: Stop RKE2 services
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop:
    - rke2-server
    - rke2-agent
  ignore_errors: true

- name: Remove RKE2 files and directories
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /var/lib/rancher/rke2
    - /etc/rancher/rke2
    - /usr/local/bin/rke2
    - /usr/local/bin/kubectl
    - /var/lib/kubelet
    - /etc/kubernetes
    - /run/k3s
    - /run/flannel
    - /etc/cni
    - /var/lib/cni

- name: Reboot host
  reboot:
    msg: "Rebooting after RKE2 cleanup"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
