---
- name: Wait for kubeconfig to be generated
  ansible.builtin.wait_for:
    path: "{{ paths.rke2.kubeconfig }}"
    state: present
    timeout: 300
  register: kubeconfig_wait

- name: Check kubeconfig file status
  ansible.builtin.stat:
    path: "{{ paths.rke2.kubeconfig }}"
  register: kubeconfig_file

- name: Ensure user .kube directory exists
  ansible.builtin.file:
    path: "{{ paths.user.kube }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "{{ file_modes.directory.default }}"

- name: Create symlink for user kubeconfig
  ansible.builtin.file:
    src: "{{ paths.rke2.kubeconfig }}"
    dest: "{{ paths.user.config }}"
    state: link
    force: true
  when: kubeconfig_file.stat.exists
