---
- name: Check if kubeconfig exists locally
  stat:
    path: "{{ kubeconfig_dest }}"
  delegate_to: localhost
  register: kubeconfig_file
  when: kubeconfig_dest is defined

- name: Wait for kubeconfig
  wait_for:
    path: /etc/rancher/rke2/rke2.yaml
    state: present
    timeout: 600

- name: Copy kubeconfig
  block:
    - name: Ensure kubeconfig directory exists
      file:
        path: "{{ kubeconfig_dest | dirname }}"
        state: directory
        mode: '0755'
      delegate_to: localhost
      when: kubeconfig_dest is defined
      
    - name: Copy kubeconfig file
      fetch:
        src: /etc/rancher/rke2/rke2.yaml
        dest: "{{ kubeconfig_dest }}"
        flat: yes
      when: kubeconfig_dest is defined and (not kubeconfig_file.stat.exists or force_kubeconfig_copy | default(false) | bool)
