---
- name: Wait for kubeconfig to be generated
  wait_for:
    path: /etc/rancher/rke2/rke2.yaml
    state: present
    timeout: 300
  register: kubeconfig_file

- name: Create .kube directory for ubuntu user
  ansible.builtin.file:
    path: /home/ubuntu/.kube
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Copy kubeconfig to user directory
  copy:
    src: /etc/rancher/rke2/rke2.yaml
    dest: /home/ubuntu/.kube/config
    remote_src: yes
    owner: ubuntu
    group: ubuntu
    mode: '0600'
  when: kubeconfig_file.stat.exists

- name: Create symlink for kubectl
  ansible.builtin.file:
    src: /var/lib/rancher/rke2/bin/kubectl
    dest: /usr/local/bin/kubectl
    state: link
    force: true

- name: Update kubeconfig server address
  ansible.builtin.replace:
    path: /home/ubuntu/.kube/config
    regexp: 'server: https://127.0.0.1:6443'
    replace: 'server: https://{{ first_server_ip }}:6443'
  when: inventory_hostname != groups['control_plane_nodes'][0]

- name: Copy kubeconfig from first control plane to workers
  ansible.builtin.copy:
    src: "{{ paths.user.kubeconfig }}"
    dest: "{{ paths.user.kubeconfig }}"
    mode: '0600'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  delegate_to: "{{ groups['control_plane_nodes'][0] }}"
  when: inventory_hostname in groups['worker_nodes']
