---
- name: Wait for kubeconfig
  ansible.builtin.wait_for:
    path: "{{ paths.base.rke2.kubeconfig }}"
    state: present
    timeout: 300
  register: kubeconfig_file

- name: Configure cluster access
  when: kubeconfig_file.stat.exists
  block:
    - name: Copy kubeconfig
      ansible.builtin.copy:
        src: "{{ paths.base.rke2.kubeconfig }}"
        dest: "{{ paths.user.config }}"
        remote_src: true
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "{{ file_modes.file.secure }}"

    - name: Update server address
      ansible.builtin.replace:
        path: "{{ paths.user.config }}"
        regexp: "server: https://127.0.0.1:6443"
        replace: "server: https://{{ first_server_ip }}:6443"
      when: inventory_hostname != groups['control_plane_nodes'][0]
