- name: Start RKE2 agent service
  ansible.builtin.systemd:
    name: rke2-agent
    state: started
    enabled: true
  register: agent_start
  until: agent_start is success
  retries: "{{ retry_standard }}"
  delay: "{{ retry_delay }}"

- name: Wait for RKE2 agent service to be fully started
  ansible.builtin.wait_for:
    timeout: 181
  register: wait_result
  retries: 12 
  delay: 15
  until: wait_result is success

- name: Wait for RKE2 agent service active state
  ansible.builtin.systemd:
    name: rke2-agent
    state: started
  register: rke2_service
  until: rke2_service.status.ActiveState == "active"
  retries: "{{ retry_extended }}"
  delay: "{{ retry_delay }}"

- name: Wait for node to be ready
  ansible.builtin.shell: |
    set -o pipefail
    {{ kubectl.command }} get nodes {{ inventory_hostname | lower }} \
      -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}'
  args:
    executable: /bin/bash
  register: node_readiness
  until: node_readiness.stdout == 'True'
  retries: "{{ wait_config.retries }}"
  delay: "{{ wait_config.delay }}"
  changed_when: false
  delegate_to: "{{ delegation_target }}"
  environment:
    KUBECONFIG: "{{ kubectl.config }}" 