---
- name: Setup control plane nodes
  ansible.builtin.include_tasks: control_plane_init.yml
  when: inventory_hostname in groups['control_plane_nodes']

- name: Verify cluster status
  ansible.builtin.include_tasks: verify_cluster.yml
  when: inventory_hostname == groups['control_plane_nodes'][0]

- name: Configure user access
  ansible.builtin.include_tasks: configure_user_access.yml
  when: inventory_hostname in groups['control_plane_nodes']

- name: Validate control plane
  ansible.builtin.include_tasks: validate_control_plane.yml
  when: inventory_hostname == groups['control_plane_nodes'][0]
