---
- name: Setup user environment
  ansible.builtin.include_tasks: setup_user.yml
  tags: [user, config]

- name: Setup first control plane node
  ansible.builtin.include_tasks: first_control_plane.yml
  when: inventory_hostname == groups['control_plane_nodes'][0]

- name: Wait for first control plane to be ready
  ansible.builtin.wait_for:
    host: 127.0.0.1
    port: 9345
    timeout: "{{ timeout_startup }}"
  delegate_to: "{{ groups['control_plane_nodes'][0] }}"
  when: inventory_hostname != groups['control_plane_nodes'][0]

- name: Setup additional control plane nodes
  ansible.builtin.include_tasks: additional_control_planes.yml
  when: inventory_hostname != groups['control_plane_nodes'][0]

- name: Configure cluster access
  ansible.builtin.include_tasks: configure_access.yml
  when: inventory_hostname in groups['control_plane_nodes']
  tags: [config, access]

- name: Verify cluster status
  ansible.builtin.include_tasks: verify_cluster.yml
  when: inventory_hostname == groups['control_plane_nodes'][0]
  tags: [verify]

- name: Configure user access
  ansible.builtin.include_tasks: configure_user_access.yml
  when: inventory_hostname in groups['control_plane_nodes']
  tags: [user, access]

- name: Validate control plane
  ansible.builtin.include_tasks: validate_control_plane.yml
  when: inventory_hostname == groups['control_plane_nodes'][0]
  tags: [validate]

- name: Verify first control plane
  ansible.builtin.include_tasks: verify_first_control_plane.yml
  when: inventory_hostname == groups['control_plane_nodes'][0]
  tags:
    - verify_control_plane
    - control_plane

- name: Include airgap setup
  ansible.builtin.include_tasks: airgap/main.yml
  when: airgap_install | default(false) | bool
