---
- name: Include user validation
  ansible.builtin.include_tasks: validate_user.yml

- name: Configure user environment
  ansible.builtin.lineinfile:
    path: "{{ paths.user.bashrc }}"
    line: "export KUBECONFIG={{ paths.rke2.kubeconfig }}"
    regexp: "^export KUBECONFIG="
    create: true

- name: Configure root environment
  ansible.builtin.lineinfile:
    path: "{{ paths.system.root_bashrc }}"
    line: "export KUBECONFIG={{ paths.rke2.kubeconfig }}"
    regexp: "^export KUBECONFIG="
    create: true
  become: true
