---
- name: Validate control plane health
  block:
    - name: Check etcd health
      ansible.builtin.command:
        cmd: "{{ paths.rke2.bin }}/kubectl get --raw /healthz/etcd"
      environment:
        KUBECONFIG: "{{ paths.rke2.kubeconfig }}"
      register: etcd_health
      until: etcd_health.stdout == "ok"
      retries: 30 # 5 minutes with 10s delay
      delay: 10
      changed_when: false
      become: true

    - name: Verify etcd pods
      ansible.builtin.shell: |
        {{ paths.rke2.bin }}/kubectl get pods -n kube-system -l component=etcd --no-headers | awk '{print $3}'
      environment:
        KUBECONFIG: "{{ paths.rke2.kubeconfig }}"
      register: etcd_pods
      become: true

    - name: Set expected etcd count
      ansible.builtin.set_fact:
        expected_etcd_count: >-
          {{
            1 if rebuilding_first_node | default(false) | bool
            else groups['control_plane_nodes'] | length
          }}

    - name: Debug etcd pods status
      ansible.builtin.debug:
        msg:
          - "Etcd pods status: {{ etcd_pods.stdout_lines }}"
          - "Expected count: {{ expected_etcd_count }}"
          - "Rebuilding first node: {{ rebuilding_first_node | default(false) }}"
          - "Current control plane nodes: {{ groups['control_plane_nodes'] | length }}"


