---
- name: Verify user variables
  ansible.builtin.assert:
    that:
      - ansible_user is defined
      - ansible_user | length > 0
    success_msg: "User configuration validated"
    fail_msg: "ansible_user must be defined and not empty"

- name: Set user home directory
  ansible.builtin.set_fact:
    user_home: "/home/{{ ansible_user }}"
