---
- name: Validate cluster deployment
  environment:
    KUBECONFIG: "{{ paths.rke2.kubeconfig }}"
  block:
    - name: Check node status
      ansible.builtin.command:
        cmd: "{{ commands.kubectl }} get nodes"
      register: node_status
      changed_when: false

    - name: Verify pod status
      ansible.builtin.include_tasks: verify_pods.yml
      vars:
        rebuilding_first_node: false
