---
- name: Validate cluster deployment
  environment:
    KUBECONFIG: "{{ paths.rke2.kubeconfig }}"
  block:
    - name: Check node status
      ansible.builtin.command:
        cmd: "{{ commands.kubectl }} get nodes"
      register: node_status
      changed_when: false

    - name: Check pod status across all namespaces
      ansible.builtin.command:
        cmd: "{{ commands.kubectl }} get pods -A"
      register: pod_status
      changed_when: false
