---
- name: Verify cluster health
  block:
    - name: Wait for all control plane nodes
      ansible.builtin.shell: |
        set -o pipefail
        READY_CP=$({{ paths.rke2.bin }}/kubectl get nodes --selector=node.kubernetes.io/instance-type=control-plane \
          -o jsonpath='{range .items[*]}{.status.conditions[?(@.type=="Ready")].status}{end}' | grep -c True)
        TOTAL_CP=$({{ paths.rke2.bin }}/kubectl get nodes --selector=node.kubernetes.io/instance-type=control-plane \
          -o name | wc -l)
        echo "Ready CP: $READY_CP, Total CP: $TOTAL_CP"
        test "$READY_CP" -eq "$TOTAL_CP"
      args:
        executable: /bin/bash
      register: cp_ready_check
      until: cp_ready_check.rc == 0
      retries: 30
      delay: 10
      changed_when: false
      environment:
        KUBECONFIG: "{{ paths.rke2.kubeconfig }}"

    - name: Verify etcd health
      ansible.builtin.shell: |
        {{ paths.rke2.bin }}/kubectl get --raw=/healthz/etcd
      register: etcd_health
      until: etcd_health.stdout == "ok"
      retries: 30
      delay: 10
      changed_when: false
      environment:
        KUBECONFIG: "{{ paths.rke2.kubeconfig }}"
