- name: Verify RKE2 installation result
  block:
    - name: Check installation script result
      assert:
        that:
          - install_result.rc == 0
          - "'unpacking tarball file to /usr/local' in install_result.stdout"
        fail_msg: |
          RKE2 installation failed:
          RC: {{ install_result.rc }}
          stdout: {{ install_result.stdout }}
          stderr: {{ install_result.stderr }}
        success_msg: "RKE2 installation script completed successfully"
      when: install_result is defined

    - name: Check essential RKE2 files
      stat:
        path: "{{ item }}"
      loop:
        - /usr/local/bin/rke2
        - /var/lib/rancher/rke2/bin/kubectl
        - /etc/rancher/rke2
      register: rke2_files

    - name: Verify all required files exist
      ansible.builtin.assert:
        that:
          - rke2_files.results | map(attribute='stat.exists') | select('true') | list | length == rke2_files.results | length
        success_msg: "All required RKE2 files are present"
        fail_msg: "Some required RKE2 files are missing"
