---
- name: Collect cluster health information
  block:
    - name: Set delegation target
      ansible.builtin.set_fact:
        delegation_target: "{{ groups['control_plane_nodes'][0] }}"

    - name: Check node status
      ansible.builtin.command:
        cmd: "{{ paths.rke2.bin }}/kubectl get nodes -o wide"
      environment:
        KUBECONFIG: "{{ paths.rke2.kubeconfig }}"
      delegate_to: "{{ delegation_target }}"
      register: node_status
      changed_when: false

    - name: Check control plane pods
      ansible.builtin.shell: |
        {{ paths.rke2.bin }}/kubectl get pods -n kube-system -l tier=control-plane -o wide
      environment:
        KUBECONFIG: "{{ paths.rke2.kubeconfig }}"
      delegate_to: "{{ delegation_target }}"
      register: pod_status
      changed_when: false
      become: true

    - name: Check etcd health
      ansible.builtin.shell: |
        {{ paths.rke2.bin }}/kubectl get --raw /healthz/etcd
      environment:
        KUBECONFIG: "{{ paths.rke2.kubeconfig }}"
      delegate_to: "{{ delegation_target }}"
      register: etcd_health
      changed_when: false
      become: true

    - name: Check API server health
      ansible.builtin.shell: |
        {{ paths.rke2.bin }}/kubectl get --raw /healthz
      environment:
        KUBECONFIG: "{{ paths.rke2.kubeconfig }}"
      delegate_to: "{{ delegation_target }}"
      register: apiserver_health
      changed_when: false
      become: true

    - name: Verify required pods are running
      ansible.builtin.shell: |
        {{ paths.rke2.bin }}/kubectl get pods -n kube-system | grep -q "{{ item }}"
      environment:
        KUBECONFIG: "{{ paths.rke2.kubeconfig }}"
      register: pod_check
      until: pod_check.rc == 0
      retries: 30
      delay: 10
      changed_when: false
      failed_when: false
      become: true
      delegate_to: "{{ delegation_target }}"
      with_items:
        - "kube-apiserver"
        - "kube-controller-manager"
        - "kube-scheduler"
        - "etcd"
      when: inventory_hostname in groups['control_plane_nodes']

    - name: Display cluster health summary
      ansible.builtin.debug:
        msg:
          - "=== RKE2 Cluster Health Summary ==="
          - "API Server: {{ 'HEALTHY' if 'ok' in apiserver_health.stdout else 'UNHEALTHY' }}"
          - "Etcd: {{ 'HEALTHY' if 'ok' in etcd_health.stdout else 'UNHEALTHY' }}"
          - ""
          - "=== Nodes ==="
          - "{{ node_status.stdout_lines }}"
          - ""
          - "=== Control Plane Pods ==="
          - "{{ pod_status.stdout_lines }}"
