---
- name: Check RKE2 service status
  ansible.builtin.systemd:
    name: rke2-server
  register: service_status

- name: Display service status
  ansible.builtin.debug:
    msg: 
      - "Service Status: {{ service_status.status.SubState }}"
      - "Active Since: {{ service_status.status.ActiveEnterTimestamp }}"

- name: Get service logs if not running
  when: service_status.status.SubState != 'running'
  block:
    - name: Collect service logs
      ansible.builtin.command: journalctl -u rke2-server.service --no-pager -n 50
      register: rke2_logs

    - name: Display service logs
      ansible.builtin.debug:
        var: rke2_logs.stdout_lines

- name: Check service initialization
  shell: |
    echo -e "\n=== Service Initialization Details ===" >> /tmp/rke2-diagnostics.log
    systemctl show rke2-server --property=StatusText,LoadState,ActiveState >> /tmp/rke2-diagnostics.log
