---
- name: Wait for all nodes to be ready
  ansible.builtin.shell: |
    set -o pipefail
    {{ paths.rke2.bin }}/kubectl get nodes | grep -v NotReady | grep Ready | wc -l
  args:
    executable: /bin/bash
  register: ready_nodes
  until: ready_nodes.stdout | int >= (groups['three_node_cluster'] | length)
  retries: 30
  delay: 10
  changed_when: false
  environment:
    KUBECONFIG: "{{ paths.rke2.kubeconfig }}"

- name: Verify cluster node status
  ansible.builtin.command:
    cmd: "{{ paths.rke2.bin }}/kubectl get nodes"
  register: node_status
  changed_when: false
  environment:
    KUBECONFIG: "{{ paths.rke2.kubeconfig }}"

- name: Display node status
  ansible.builtin.debug:
    var: node_status.stdout_lines
