---
- name: Quick service verification
  block:
    - name: Check RKE2 service status
      ansible.builtin.systemd:
        name: rke2-server
      register: service_status

    - name: Fail fast if service isn't running
      ansible.builtin.fail:
        msg: |
          RKE2 service failed to start properly.
          Status: {{ service_status.status.SubState }}
          See: journalctl -u rke2-server -n 50
      when: service_status.status.SubState != 'running'
