---
- name: Verify cluster health
  block:
    - name: Wait for all control plane nodes
      ansible.builtin.shell: |
        set -o pipefail
        READY_CP=$({{ paths.rke2.bin }}/kubectl get nodes --selector=node.kubernetes.io/instance-type=control-plane \
          -o jsonpath='{range .items[*]}{.status.conditions[?(@.type=="Ready")].status}{end}' | grep -c True)
        TOTAL_CP=$({{ paths.rke2.bin }}/kubectl get nodes --selector=node.kubernetes.io/instance-type=control-plane \
          -o name | wc -l)
        echo "Ready CP: $READY_CP, Total CP: $TOTAL_CP"
        test "$READY_CP" -eq "$TOTAL_CP"
      args:
        executable: /bin/bash
      register: cp_ready_check
      until: cp_ready_check.rc == 0
      retries: "{{ retry_extended }}"
      delay: "{{ retry_delay }}"
      changed_when: false
      environment:
        KUBECONFIG: "{{ paths.rke2.kubeconfig }}"

    - name: Verify etcd health
      ansible.builtin.shell: |
        {{ paths.rke2.bin }}/kubectl get --raw=/healthz/etcd
      register: etcd_health
      until: etcd_health.stdout == "ok"
      retries: "{{ retry_extended }}"
      delay: "{{ retry_delay }}"
      changed_when: false
      environment:
        KUBECONFIG: "{{ paths.rke2.kubeconfig }}"

- name: Verify RKE2 file permissions
  ansible.builtin.stat:
    path: "{{ item }}"
  register: rke2_files
  loop:
    - "{{ paths.rke2.kubeconfig }}"
    - "{{ paths.rke2.data }}"
    - "{{ paths.rke2.bin }}"
  failed_when: false
  changed_when: false

- name: Debug RKE2 file permissions
  ansible.builtin.debug:
    msg: "{{ item.item }} permissions: {{ item.stat.mode }}"
  loop: "{{ rke2_files.results }}"
  when: item.stat.exists

- name: Verify kubectl configuration
  ansible.builtin.stat:
    path: "{{ paths.rke2.kubeconfig }}"
  register: kubeconfig_stat

- name: Fail if kubeconfig doesn't exist
  ansible.builtin.fail:
    msg: "RKE2 kubeconfig not found at {{ paths.rke2.kubeconfig }}"
  when: not kubeconfig_stat.stat.exists
