---
- name: Create RKE2 config directory on workers
  ansible.builtin.file:
    path: /etc/rancher/rke2
    state: directory
    mode: '0755'
    owner: root
    group: root
  become: true

- name: Configure worker nodes
  block:
    - name: Ensure token is defined
      ansible.builtin.assert:
        that:
          - rke2_token is defined
          - rke2_token | length > 0
        fail_msg: "RKE2 token must be defined for worker nodes"

    - name: Configure RKE2 for workers
      ansible.builtin.template:
        src: config.yaml.j2
        dest: /etc/rancher/rke2/config.yaml
        mode: '0600'

    - name: Verify token from control plane
      ansible.builtin.debug:
        msg:
          - "First control plane: {{ groups['control_plane_nodes'][0] }}"
          - "Token from CP: {{ hostvars[groups['control_plane_nodes'][0]].rke2_token | default('UNDEFINED') }}"
      when: not hostvars[groups['control_plane_nodes'][0]].rke2_token is defined
  rescue:
    - name: Debug token information
      ansible.builtin.debug:
        msg: 
          - "Inventory Hostname: {{ inventory_hostname }}"
          - "Defined Variables: {{ hostvars[inventory_hostname] }}"
      failed_when: true
