---
- name: Install RKE2 agent
  ansible.builtin.shell: |
    export INSTALL_RKE2_TYPE=agent
    export INSTALL_RKE2_VERSION={{ rke2_version }}
    sh /tmp/install.sh
  args:
    creates: /usr/local/bin/rke2
