---
# RKE2 Cluster Default Variables

# Cluster Configuration
cluster_type: "six_node"
first_server_ip: ""

# Installation Paths
paths:
  base:
    rke2:
      config: /etc/rancher/rke2
      data: /var/lib/rancher/rke2
      bin: /var/lib/rancher/rke2/bin
      kubeconfig: /etc/rancher/rke2/rke2.yaml
    system:
      bin: /usr/local/bin
      root:
        home: /root
        kube: /root/.kube
        config: /root/.kube/config
        bashrc: /root/.bashrc
  user:
    home: "/home/{{ ansible_user }}"
    kube: "/home/{{ ansible_user }}/.kube"
    config: "/home/{{ ansible_user }}/.kube/config"
    ssh: "/home/{{ ansible_user }}/.ssh"
    bashrc: "/home/{{ ansible_user }}/.bashrc"

# Wait Configuration
wait_config:
  retries: 30
  delay: 10

# Installation Types
install_types:
  server: server
  agent: agent

# Services
services:
  server: rke2-server
  agent: rke2-agent

# Commands
commands:
  rke2: /usr/local/bin/rke2
  kubectl: /usr/local/bin/kubectl

# Network Configuration
network:
  plugin: cilium
  cni_version: v1.14.0

# Additional Add-ons
install_cilium: true
install_metrics_server: true
install_dashboard: false

# Security Configuration
pod_security_admission:
  enabled: true
  default_profile: baseline

# Resource Constraints
system_requirements:
  min_cpu_cores: 2
  min_memory_mb: 4096
  max_memory_mb: 16384

# Logging Configuration
logging:
  level: info
  output_file: /var/log/rke2/rke2.log

# Experimental Features
experimental:
  enable_custom_registries: false
  custom_registries_path: /etc/rancher/rke2/registries.yaml

# Default configurations
default_config:
  token: rke2-cluster-token
  cni: canal
  disable:
    - rke2-ingress-nginx
  node-taint: []

# Feature flags
enable_monitoring: true
enable_ingress: true

# Add these timeout and retry settings
rke2_wait_settings:
  timeout: 300
  retries: 30
  delay: 10
  connect_timeout: 5

# Add these port definitions
rke2_ports:
  supervisor: 9345
  api: 6443
  etcd_client: 2379
  etcd_peer: 2380

# Add these state definitions
rke2_states:
  STARTING:
    pattern: "Starting rke2-server"
    completed: false
  INIT:
    pattern: "Cluster-init mode enabled"
    completed: false
  RUNNING:
    pattern: "Running kube-apiserver"
    completed: false

# Add these monitoring settings
rke2_monitor_timeout: 600  # 10 minutes
rke2_monitor_interval: 10  # 10 seconds

# Base system paths that don't change
base_paths:
  rke2:
    config: /etc/rancher/rke2
    data: /var/lib/rancher/rke2
    bin: /var/lib/rancher/rke2/bin
    kubeconfig: /etc/rancher/rke2/rke2.yaml

# Default file permissions
file_modes:
  directory:
    default: '0755'
    secure: '0700'
  file:
    default: '0644'
    secure: '0600'
