---
- name: restart rke2-server
  ansible.builtin.systemd:
    name: rke2-server
    state: restarted
    daemon_reload: yes
  listen: "restart rke2"

- name: restart rke2-agent
  ansible.builtin.systemd:
    name: rke2-agent
    state: restarted
    daemon_reload: yes
  listen: "restart rke2"

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: reload sysctl
  ansible.builtin.command: sysctl --system
  changed_when: false

- name: wait for node ready
  ansible.builtin.command:
    cmd: "kubectl get nodes {{ inventory_hostname }} -o jsonpath='{.status.conditions[?(@.type==\"Ready\")].status}'"
  environment:
    KUBECONFIG: /etc/rancher/rke2/rke2.yaml
  register: node_status
  until: node_status.stdout == "True"
  retries: 30
  delay: 10
  changed_when: false
  delegate_to: "{{ groups['three_node_control_plane' if cluster_type == 'three_node' else 'control_plane_nodes'][0] }}"
