---
- name: Create local download directories
  ansible.builtin.file:
    path: "{{ version_dir }}"
    state: directory
    mode: '0755'
  delegate_to: localhost
  become: false

- name: Download RKE2 images
  ansible.builtin.get_url:
    url: "{{ airgap.download.base_url }}/{{ rke2_version_clean }}/rke2-images.linux-{{ item }}.tar.zst"
    dest: "{{ version_dir }}/rke2-images.linux-{{ item }}.tar.zst"
    mode: '0644'
  loop: "{{ airgap.architectures }}"
  delegate_to: localhost
  become: false
  when: not image_files.results | selectattr('item', 'equalto', item) | map(attribute='stat.exists') | select('true') | list | length 