---
- name: Create local download directories
  ansible.builtin.file:
    path: "{{ version_dir }}"
    state: directory
    mode: '0755'
  delegate_to: localhost
  become: false
  run_once: true
  when: not airgap_verified | default(false)

- name: Download RKE2 images
  get_url:
    url: "{{ airgap.urls.base | replace('+', '%2B') }}/rke2-images.linux-{{ item }}.tar.zst"
    dest: "{{ version_dir }}/rke2-images.linux-{{ item }}.tar.zst"
    mode: "{{ airgap.file_modes.downloads }}"
    timeout: 300
    force: "{{ not airgap_verified | default(true) }}"
  loop: "{{ airgap.architectures }}"
  delegate_to: localhost
  become: false
  when: not airgap_verified | default(false) 