---
- name: Include airgap variables
  ansible.builtin.include_vars:
    file: "{{ role_path }}/vars/airgap.yml"

- name: Extract RKE2 version
  ansible.builtin.set_fact:
    rke2_version_clean: "{{ rke2_version.stdout | default(rke2_version) }}"

- name: Set version directory path
  ansible.builtin.set_fact:
    version_dir: "{{ airgap.paths.downloads }}/{{ rke2_version_clean }}"

- name: Map architecture to RKE2 format
  ansible.builtin.set_fact:
    rke2_arch: >-
      {{
        'amd64' if ansible_architecture == 'x86_64'
        else 'arm64' if ansible_architecture in ['aarch64', 'arm64']
        else ansible_architecture
      }}

- name: Include verification tasks
  ansible.builtin.include_tasks: verify.yml

- name: Include download tasks
  ansible.builtin.include_tasks: download.yml
  when: not verification_passed | default(false)

- name: Include deployment tasks
  ansible.builtin.include_tasks: deploy.yml 