write-kubeconfig-mode: '0644'
tls-san:
- 127.0.0.1
- 192.168.1.23
- 192.168.1.24
- 192.168.1.25
- 192.168.1.52
- 192.168.1.54
- 192.168.1.55
- k1
- k1.home.arpa
- k2
- k2.home.arpa
- k3
- k3.home.arpa
- kubernetes
- kubernetes.default
- kubernetes.default.svc
- kubernetes.default.svc.cluster.local
- localhost
- node7
- node7.home.arpa
- node8
- node8.home.arpa
- node9
- node9.home.arpa
node-name: k3
token: test123
server: https://192.168.1.23:9345
node-label:
- node.kubernetes.io/instance-type=control-plane
- kubernetes.io/hostname=k3
- workload.type=control-plane
node-taint:
- CriticalAddonsOnly=true:NoSchedule
