#!/usr/bin/env python3

import yaml
import os
import ipaddress
import sys


def validate_node_data(nodes):
    """Validate node data format and IP addresses."""
    for hostname, ip in nodes:
        if not hostname or not isinstance(hostname, str):
            raise ValueError(f"Invalid hostname: {hostname}")
        try:
            ipaddress.ip_address(ip)
        except ValueError:
            raise ValueError(f"Invalid IP address: {ip}")
    return True


def write_inventory_file(inventory_data, file_path):
    """Write inventory data to a YAML file."""
    header = """---
#####################################################################
# WARNING: THIS IS A GENERATED FILE. DO NOT EDIT DIRECTLY!
#
# This file is automatically generated by scripts/generate_inventory.py
# To make changes, modify inventory/hosts.txt and regenerate this file.
#####################################################################
"""
    os.makedirs(os.path.dirname(file_path), exist_ok=True)
    with open(file_path, 'w') as f:
        f.write(header)
        yaml.dump(inventory_data, f, default_flow_style=False, sort_keys=False)


def parse_host_line(line):
    """Parse a host line into hostname and host vars."""
    parts = line.strip().split()
    host_vars = {}
    hostname = parts[0]

    if len(parts) > 1:
        if '=' not in parts[1]:
            host_vars['ansible_host'] = parts[1]

        for part in parts[1:]:
            if '=' in part:
                key, value = part.split('=', 1)
                if key == 'agent_mount_device':
                    host_vars['mounts'] = {
                        'agent': {
                            'enabled': True,
                            'device': value,
                            'fstype': 'xfs',
                            'opts': 'defaults,pquota,prjquota'
                        }
                    }

    return hostname, host_vars


def generate_inventory(hosts_file):
    """Generate inventory structure from a hosts.txt file."""
    inventory = {
        'all': {
            'children': {
                'six_node_cluster': {
                    'children': {
                        'control_plane_nodes': {'hosts': {}},
                        'worker_nodes': {'hosts': {}}
                    }
                }
            },
            'vars': {}
        }
    }

    ip_mappings = {}
    current_group = None

    with open(hosts_file, 'r') as f:
        lines = f.readlines()

    for line in lines:
        line = line.strip()
        if not line or line.startswith('#'):
            continue

        if line.startswith('[') and line.endswith(']'):
            current_group = line[1:-1]
            continue

        if current_group == 'vars':
            if '=' in line:
                key, value = line.split('=', 1)
                inventory['all']['vars'][key.strip()] = value.strip()
        elif current_group == 'six_node':
            hostname, vars = parse_host_line(line)
            ip_mappings[hostname] = vars
        elif current_group in ['control_plane_nodes', 'worker_nodes']:
            hostname = line.strip()
            if hostname in ip_mappings:
                node_vars = ip_mappings[hostname]
                inventory['all']['children']['six_node_cluster']['children'][current_group]['hosts'][hostname] = node_vars

    inventory['all']['vars'].update({
        'ansible_user': 'ubuntu',
        'ansible_python_interpreter': '/usr/bin/python3',
        'ansible_ssh_common_args': '-o StrictHostKeyChecking=no',
        'ssh_public_key_path': inventory['all']['vars'].get('ssh_public_key_path', '~/.ssh/id_ed25519.pub'),
        'rke2_version': inventory['all']['vars'].get('rke2_version', 'v1.31.4+rke2r1')
    })

    return inventory


def main():
    if len(sys.argv) != 2:
        print("Usage: generate_inventory.py <hosts_file>")
        sys.exit(1)

    hosts_file = sys.argv[1]
    output_file = 'inventory/rke2.yml'

    try:
        inventory = generate_inventory(hosts_file)
        write_inventory_file(inventory, output_file)
        print(f"Generated inventory file: {output_file}")
    except Exception as e:
        print(f"Error: {str(e)}", file=sys.stderr)
        sys.exit(1)


if __name__ == '__main__':
    main()
