---
- name: Create RKE2 config directory
  ansible.builtin.file:
    path: "{{ paths.rke2.config }}"
    state: directory
    mode: '0755'

- name: Configure additional control plane nodes
  ansible.builtin.template:
    src: config.yaml.j2
    dest: "{{ paths.rke2.config }}/config.yaml"
    mode: '0644'

- name: Install RKE2 server
  ansible.builtin.shell: |
    curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE=server sh -
  args:
    creates: "{{ commands.rke2 }}"

- name: Enable and start RKE2 server
  ansible.builtin.systemd:
    name: rke2-server
    enabled: yes
    state: started
