---
- name: Check for RKE2 installation markers
  ansible.builtin.stat:
    path: "{{ item }}"
  register: rke2_files
  with_items:
    - /usr/local/bin/rke2
    - /var/lib/rancher/rke2/bin/kubectl
    - /etc/systemd/system/rke2-server.service

- name: Set fact about RKE2 installation status
  ansible.builtin.set_fact:
    rke2_is_installed: "{{ rke2_files.results | selectattr('stat.exists') | list | length > 0 }}"

- name: Show RKE2 installation status
  ansible.builtin.debug:
    msg: "RKE2 is {{ 'installed' if rke2_is_installed else 'not installed' }}"
