---
- name: Stop RKE2 services
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items:
    - rke2-server
    - rke2-agent
  ignore_errors: yes

- name: Run RKE2 uninstall script
  shell: |
    if [ -f /usr/local/bin/rke2-uninstall.sh ]; then
      /usr/local/bin/rke2-uninstall.sh
    else
      echo "RKE2 uninstall script not found - likely already uninstalled"
    fi
  register: uninstall_output
  ignore_errors: yes

- name: Debug - Show uninstall output
  debug:
    var: uninstall_output.stdout_lines
  when: uninstall_output.stdout_lines is defined

- name: Reload systemd
  systemd:
    daemon_reload: yes