---
# Setup first control plane node
- name: Setup first control plane node
  include_tasks: first_control_plane.yml
  when: inventory_hostname == groups['three_node_control_plane'].0

# Setup additional control plane nodes
- name: Setup additional control plane nodes
  include_tasks: additional_control_planes.yml
  when: 
    - inventory_hostname != groups['three_node_control_plane'].0
    - inventory_hostname in groups['three_node_cluster']

# Wait for cluster to be ready and verify
- name: Verify cluster status
  include_tasks: verify_cluster.yml
  when: inventory_hostname == groups['three_node_control_plane'].0

# Configure user access
- name: Configure user access
  include_tasks: configure_user_access.yml


