- name: Verify system requirements
  assert:
    that:
      - ansible_memtotal_mb >= 2048
      - ansible_processor_cores >= 2
    fail_msg: "System does not meet minimum requirements"
    success_msg: "System meets minimum requirements"

- name: Check network connectivity
  wait_for:
    host: "{{ first_server_ip }}"
    port: 9345
    timeout: 30
    state: started
  when: inventory_hostname != groups[cluster_type + '_control_plane'][0]
  register: network_check
  until: not network_check.failed | default(false)
  retries: 6
  delay: 10
  ignore_errors: yes

- name: Debug - Network connectivity check details
  debug:
    msg: 
      - "Host: {{ inventory_hostname }}"
      - "Target: {{ first_server_ip }}:9345"
      - "Result: {{ network_check }}"
  when: inventory_hostname != groups[cluster_type + '_control_plane'][0]

- name: Fail if network connectivity check failed
  fail:
    msg: "Network connectivity check failed for {{ inventory_hostname }} to {{ first_server_ip }}:9345"
  when: 
    - inventory_hostname != groups[cluster_type + '_control_plane'][0]
    - network_check is defined
    - network_check.failed | default(false)